#!/usr/env/python

from PySide import QtCore, QtGui, QtDeclarative

class iTip(QtCore.QObject):
    @QtCore.Slot(str, str)
    def search(self, line, station):
        print line
        print station

if __name__ == '__main__':
    import sys

    app = QtGui.QApplication(sys.argv)

    view = QtDeclarative.QDeclarativeView()

    # instantiate the Python object
    itip = iTip()

    # expose the object to QML
    context = view.rootContext()
    context.setContextProperty("itip", itip)

    view.setSource(QtCore.QUrl('gotovienna/qml/main.qml'))
    view.show()

    sys.exit(app.exec_())
