# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyWienerLinien.ui'
#
# Created: Tue Mar  8 22:48:01 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnSearch = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearch.sizePolicy().hasHeightForWidth())
        self.btnSearch.setSizePolicy(sizePolicy)
        self.btnSearch.setObjectName("btnSearch")
        self.gridLayout_3.addWidget(self.btnSearch, 5, 1, 1, 1)
        self.comboDestination = QtGui.QComboBox(self.centralwidget)
        self.comboDestination.setObjectName("comboDestination")
        self.comboDestination.addItem("")
        self.comboDestination.addItem("")
        self.comboDestination.addItem("")
        self.gridLayout_3.addWidget(self.comboDestination, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 2, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 2, 1)
        self.editOrigin = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editOrigin.sizePolicy().hasHeightForWidth())
        self.editOrigin.setSizePolicy(sizePolicy)
        self.editOrigin.setEditable(True)
        self.editOrigin.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.editOrigin.setObjectName("editOrigin")
        self.gridLayout_3.addWidget(self.editOrigin, 2, 1, 1, 1)
        self.editDestination = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editDestination.sizePolicy().hasHeightForWidth())
        self.editDestination.setSizePolicy(sizePolicy)
        self.editDestination.setEditable(True)
        self.editDestination.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.editDestination.setObjectName("editDestination")
        self.gridLayout_3.addWidget(self.editDestination, 4, 1, 1, 1)
        self.comboOrigin = QtGui.QComboBox(self.centralwidget)
        self.comboOrigin.setObjectName("comboOrigin")
        self.comboOrigin.addItem("")
        self.comboOrigin.addItem("")
        self.comboOrigin.addItem("")
        self.gridLayout_3.addWidget(self.comboOrigin, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionToggle = QtGui.QAction(MainWindow)
        self.actionToggle.setObjectName("actionToggle")
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionToggle)
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.editOrigin, self.comboOrigin)
        MainWindow.setTabOrder(self.comboOrigin, self.editDestination)
        MainWindow.setTabOrder(self.editDestination, self.comboDestination)
        MainWindow.setTabOrder(self.comboDestination, self.btnSearch)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyWienerLinien", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearch.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDestination.setItemText(0, QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDestination.setItemText(1, QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDestination.setItemText(2, QtGui.QApplication.translate("MainWindow", "POI", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Origin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOrigin.setItemText(0, QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOrigin.setItemText(1, QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.comboOrigin.setItemText(2, QtGui.QApplication.translate("MainWindow", "POI", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggle.setText(QtGui.QApplication.translate("MainWindow", "Toggle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggle.setIconText(QtGui.QApplication.translate("MainWindow", "Toggle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggle.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToggle.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))

